name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    # Set up PHP
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'

    # Check out the repository
    - uses: actions/checkout@v4

    # Copy the .env file
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # Install dependencies
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # Generate the application key
    - name: Generate key
      run: php artisan key:generate

    # Set proper permissions for storage and cache
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Set up MySQL Database
    - name: Setup MySQL Database
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: starter_db
        DB_USERNAME: starter_user
        DB_PASSWORD: password
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo service mysql start
        mysql -e "CREATE DATABASE IF NOT EXISTS starter_db;"
        mysql -e "CREATE USER IF NOT EXISTS 'starter_user'@'%' IDENTIFIED BY 'password';"
        mysql -e "GRANT ALL PRIVILEGES ON starter_db.* TO 'starter_user'@'%';"
        mysql -e "FLUSH PRIVILEGES;"

    # Run migrations and tests
    - name: Run Migrations and Tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: starter_db
        DB_USERNAME: starter_user
        DB_PASSWORD: password
      run: |
        php artisan migrate --force
        php artisan test
